name: Compile
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    Compilation:
        name: Compilation
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project
              uses: actions/checkout@v3

            - name: Use Node.js v18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: NPM Cache Clean
              run: npm cache clean --force
            
            - name: Delete package-lock.json
              run: rm -rf package-lock.json

            - name: Delete node_modules
              run: rm -rf node_modules

            - name: Install Prisma CLIs
              run: npm install -g prisma prisma-import
              
            - name: Generate Prisma Schema
              run: prisma-import -s "prisma/**/*.prisma" --output "schema.prisma" --force
                  

            - name: Generate Prisma Client
              run: prisma generate

            - name: Install NPM dependencies
              run: npm install

            - name: Run TSC
              run: npx tsc
