name: Compile
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    Compilation:
        name: Compilation
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project
              uses: actions/checkout@v3

            - name: Use Node.js v18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Prisma CLI
              run: npm install -g prisma

            - name: Generate Prisma Client
              run: prisma generate

            # This is required as installing arcadia before anything will cause this workflow to fail.
            - name: Remove Arcadia
              run: npm remove bismuthmoe/arcadia

            - name: Install NPM dependencies
              run: npm install
              
            - name: Install Arcadia
              run: npm install bismuthmoe/arcadia

            - name: Run TSC
              run: npx tsc
