name: Compile
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    Compilation:
        name: Compilation
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project
              uses: actions/checkout@v3

            - name: Use Node.js v18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Prisma CLI
              run: npm install prisma && npm i @prisma/client
              
            - name: Generate Prisma Schema
              run: npx prisma-import -s "prisma/**/*.prisma" --output "schema.prisma" --force

            - name: Generate Prisma Client
              run: npx prisma generate

            - name: Install NPM dependencies
              run: npm install

            - name: Run TSC
              run: npx tsc
